### PR TITLE
Add boot-strap file to resolve auto-loader path (fix #334)

### LINKED ISSUE #334: concise can only be run from vendor parent directory
At the top of `bin/concise` is the following:

```php
require_once('vendor/autoload.php');
```

Because unqualified include paths are relative to the current working directory, this means you can only run `concise` from the parent directory of the `vendor` folder. Attempting to run it from elsewhere will fail:

```
/tmp % composer require -q --dev 'elliotchance/concise'
/tmp % vendor/bin/concise 2>&1 | head -1
Concise v2.1.0 Photon by Elliot Chance.
/tmp % cd vendor
vendor % bin/concise 2>&1 | head -1
PHP Warning:  require_once(vendor/autoload.php): failed to open stream: No such file or directory in /private/tmp/vendor/elliotchance/concise/bin/concise on line 4
```

To fix this you could have it resolve like this, which is similar to how PHPUnit does it:

```php
foreach ( [__DIR__ . '/../vendor/autoload.php', __DIR__ . '/../../../autoload.php'] as $file ) {
    if ( file_exists($file) ) {
        require $file;
        break;
    }
}
```

This way you can run it no matter what the current working directory is.

I would just submit a PR for this but it requires adding the same code to both `concise` and `concise-init`, so i wanted to get your thoughts on how you'd want to address that in a DRY way. I think the typical thing would be to add a `src/bootstrap.php` that handles auto-loader resolution.

### PR DESCRIPTION
**Pull request by okdana**
#334

---
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/concise/335)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/concise/335)*

**Comment by elliotchance** [comment]
The code review is fine, but it looks like Travis didn't run a build so Scrutinizer failed. I have enabled PRs on Travis, but it looks like I can't manually trigger a build. Please make some change to generate a new commit. If that doesn't trigger a build I'll just merge it in.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/concise/335#-:-KOB7CKFnCS18l2buSv6:-1453849281)*

**Comment by okdana** [comment]
Did that work?

**Comment by elliotchance** [comment]
@okdana - all good now, thank you!

**Comment by elliotchance** [comment]
https://github.com/elliotchance/concise/releases/tag/v2.2.1

**Pull request merged**
