### PR TITLE
Add support for PHP 7

### PR DESCRIPTION
**Pull request by elliotchance**
[Review on Reviewable](https://reviewable.io/reviews/elliotchance/concise/328)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/elliotchance/concise/328)*

**Comment by ostrolucky** [comment]
@elliotchance Is PHP7 support still missing? I wanted to try concise since it looks interesting, but I'm not going to do even that since this project looks pretty much dead :( Is there a recommended alternative? Maybe https://github.com/atoum/atoum?

**Comment by elliotchance** [comment]
Hi @ostrolucky - it's true I haven't put any new features into concise for a while. But it's still heavily used by the company I work for. We simply haven't upgraded to PHP7 yet.

I have a feeling I know why those couple of tests are failing, I'll investigate now.

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/concise/328)*

**Comment by elliotchance** [comment]
@ostrolucky this has been merged and released as v2.1.2.

**Pull request merged**
